import {products} from '../../products';
import {notFound} from 'next/navigation';
import {ArrowLeft,ArrowUpRight,Leaf} from 'lucide-react';
export function generateStaticParams(){return products.map(p=>({slug:p.id}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.id===slug);return {title:p?`${p.blend} aus ${p.country} — Globe Spices`:'Gewürz nicht gefunden',description:p?.description};}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params,p=products.find(p=>p.id===slug);if(!p)notFound();
 return <><header className="site-header"><a className="wordmark" href="/">GLOBE SPICES<span>SPICES FROM AROUND THE WORLD</span></a><a className="back-link" href={`/#${p.id}`}><ArrowLeft size={17}/> Zur Gewürzreise</a></header><main className="detail" style={{'--country':p.color} as React.CSSProperties}><div className="detail-photo"><img src={p.detailImage} alt={`${p.country} ${p.blend} mit den Zutaten der Gewürzmischung`} width="1200" height="1200"/></div><div className="detail-copy"><p className="eyebrow">{p.country.toUpperCase()}</p><h1>{p.blend}</h1><p className="tasting-note">{p.note}</p><div className="detail-block detail-overview"><h2>Über die Mischung</h2><p>{p.description}</p></div><div className="detail-block"><h2>Passt wunderbar zu</h2><p>{p.use}</p></div><div className="detail-block"><h2>Zutaten</h2><ul className="ingredient-list">{p.ingredients.map(([name,amount])=><li key={name}><span>{name}</span><strong>{amount}</strong></li>)}</ul><p className="allergen-note">{p.allergens}</p></div><div className="recipe"><Leaf size={22}/><p className="eyebrow">EINE IDEE FÜR DEINE KÜCHE</p><h2>{p.idea}</h2><p>{p.recipe}</p></div><a className="text-link" href="https://www.instagram.com/globe_spices/" target="_blank" rel="noreferrer">Neuigkeiten von Globe Spices <ArrowUpRight size={18}/></a></div></main><section className="detail-more"><p className="eyebrow">DEINE REISE GEHT WEITER</p><div>{products.filter(x=>x.id!==slug).map(x=><a href={`/gewuerze/${x.id}`} key={x.id}>{x.country}<span>{x.blend}</span><ArrowUpRight size={20}/></a>)}</div></section><footer><a className="wordmark" href="/">GLOBE SPICES</a><a href="/#kollektion">Alle Gewürze <ArrowUpRight size={16}/></a></footer></>;
}
